SELECT
    ORDER_ID,
    SHIPPING_ADDRESS,
    PAYMENT_INFO,
    ORDER_AT AS ORDER_AT_TS,
    STATE,
    SESSION_ID,
    TRY_TO_NUMBER(REPLACE(REPLACE(SHIPPING_COST, 'USD', ''), ' ', '')) AS SHIPPING_COST,
    CLIENT_NAME,
    PHONE,
    TAX_RATE,
    PAYMENT_METHOD,
    _FIVETRAN_ID,
    _FIVETRAN_DELETED AS _FIVETRAN_DELETED_BOOLEAN,
    _FIVETRAN_SYNCED AS _FIVETRAN_SYNCED_TS
FROM {{ source('SNOWFLAKE_LOAD_WEB_SCHEMA', 'ORDERS') }}