SELECT
    ITEM_VIEW_AT AS ITEM_VIEW_AT_TS,
    SESSION_ID,
    ADD_TO_CART_QUANTITY,
    REMOVE_FROM_CART_QUANTITY,
    PRICE_PER_UNIT,
    LOWER(REPLACE(ITEM_NAME,' ','_')) AS ITEM_NAME,
    _FIVETRAN_ID,
    _FIVETRAN_DELETED AS _FIVETRAN_DELETED_BOOLEAN,
    _FIVETRAN_SYNCED AS _FIVETRAN_SYNCED_TS
FROM {{ source('SNOWFLAKE_LOAD_WEB_SCHEMA', 'ITEM_VIEWS') }}