SELECT
    ORDER_ID,
    SHIPPING_ADDRESS,
    PAYMENT_INFO,
    ORDER_AT AS ORDER_AT_TS,
    STATE,
    SESSION_ID,
    CAST(TRIM(REPLACE(SHIPPING_COST, 'USD', '')) AS FLOAT) AS SHIPPING_COST,
    CLIENT_NAME,
    PHONE,
    TAX_RATE,
    PAYMENT_METHOD,
    _FIVETRAN_ID,
    _FIVETRAN_DELETED AS _FIVETRAN_DELETED_BOOLEAN,
    _FIVETRAN_SYNCED AS _FIVETRAN_SYNCED_TS
FROM (
    SELECT *, ROW_NUMBER() OVER (PARTITION BY ORDER_ID ORDER BY ORDER_AT) AS ROW_NUM
    FROM {{ source('SNOWFLAKE_LOAD_WEB_SCHEMA', 'ORDERS') }}
)
WHERE ROW_NUM = 1
    
    