SELECT
    VIEW_AT AS VIEW_AT_TS,
    SESSION_ID,
    PAGE_NAME,
    _FIVETRAN_ID,
    _FIVETRAN_DELETED AS _FIVETRAN_DELETED_BOOLEAN,
    _FIVETRAN_SYNCED AS _FIVETRAN_SYNCED_TS
FROM {{ source('SNOWFLAKE_LOAD_WEB_SCHEMA', 'PAGE_VIEWS') }}