SELECT 
    _FILE,
    _LINE,
    _MODIFIED AS _MODIFIED_TS,
    _FIVETRAN_SYNCED AS _FIVETRAN_SYNCED_TS,
    RETURNED_AT AS RETURNED_AT_DATE,
    CAST(ORDER_ID AS STRING) AS ORDER_ID,
    CASE WHEN IS_REFUNDED = 'yes' THEN TRUE WHEN IS_REFUNDED = 'no' THEN FALSE ELSE NULL END AS IS_REFUNDED_BOOLEAN
FROM (
    SELECT *, ROW_NUMBER() OVER (PARTITION BY ORDER_ID ORDER BY RETURNED_AT) AS ROW_NUM
    FROM {{ source('google_drive', 'RETURNS') }}
)
WHERE ROW_NUM = 1