SELECT 
    _FILE,
    _LINE,
    _MODIFIED AS _MODIFIED_TS,
    _FIVETRAN_SYNCED AS _FIVETRAN_SYNCED_TS,
    DATE AS EXPENSES_DATE,
    REPLACE(EXPENSE_TYPE,' ','_') AS EXPENSE_TYPE,
    CAST(TRIM(REPLACE(EXPENSE_AMOUNT, '$', '')) AS FLOAT) AS EXPENSE_AMOUNT
FROM {{ source('google_drive', 'EXPENSES') }}