SELECT 
    _FILE,
    _LINE,
    _MODIFIED AS _MODIFIED_TS,
    _FIVETRAN_SYNCED AS _FIVETRAN_SYNCED_TS,
    CAST(EMPLOYEE_ID AS STRING) AS EMPLOYEE_ID,
    CAST(REPLACE(HIRE_DATE, 'day ', '') AS DATE) AS EMPLOYEE_HIRE_DATE,
    NAME AS EMPLOYEE_NAME,
    CITY AS EMPLOYEE_CITY ,
    ADDRESS AS EMPLOYEE_ADDRESS,
    TITLE AS EMPLOYEE_TITLES,
    ANNUAL_SALARY AS EMPLOYEE_ANNUAL_SALARY
FROM {{source('google_drive', 'HR_JOINS')}}