version: 2

sources:
  - name: google_drive
    database: LOAD
    schema: GOOGLE_DRIVE
    tables:
     - name: EXPENSES
     - name: HR_JOINS
     - name: HR_QUITS
     - name: RETURNS
  - name: web
    database: LOAD
    schema: SNOWFLAKE_LOAD_WEB_SCHEMA
    tables:
     - name: ITEM_VIEWS
     - name: ORDERS
     - name: PAGE_VIEWS
     - name: SESSIONS